sock.recv(1024).decode("utf-8") instead of "ascii" (#21)
Returned data on socket might contain non-ascii values in scan.
  File "/.../netdisco-0.6.1-py3.5.egg/netdisco/ssdp.py", line 235, in scan
    response = sock.recv(1024).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 53: ordinal not in range(128)

I had nothing but ascii in the output from python -m netdisco, but there was obviously something in the packets...

MiniDLNA sent DATE localized...